version: 2

jobs:
  build:
      docker:
        - image: circleci/python:3
      steps:
        - checkout
        - run:
            name: Install tox
            command: sudo pip install tox
        - run:
            name: Run tests
            command: tox

workflows:
  version: 2
  pytest-csv:
    jobs:
      - build
